#!/usr/bin/env bash

### configuration

_BACKUP_HOME=/mnt/nas

#   Backup target (not endwith /).
declare -a _BACKUP_TARGETS
_BACKUP_TARGETS=(\
    /etc/pdns \
    /var/lib/pdns \
    /etc/pdns-recursor \
    /etc/dirsrv \
    /etc/postfix \
    )

### main
_LHOME=$(dirname "$0");
_LNAME=$(basename "$0");
_LTITLE=$(basename "$0" .sh);
_LAPATH=$(cd "$_LHOME"; pwd);
_TIMESTAMP=$(date +"%Y-%m-%d.%H%M%S.%s");

### Check user (root)
[ $(id -g) -eq 0 ] || {
    echo "FATAL: This script must be run by root.">&2;
    exit -1;
}

### Check configurtion
echo "$_BACKUP_HOME" | egrep '^$|^(/|/bin|/boot|/dev|/etc|/home|/lib|/lib64|/media|/mnt|/opt|/proc|/root|/run|/sbin|/srv|/sys|/tmp|/usr|/var)$' >/dev/null 2>&1 && {
    echo "FATAL: Can not use \"$_BACKUP_HOME\" (system dir such as "/", "/bin" and the other).">&2;
    exit 3;
}

### Check if mounted.
LANG=C mount | grep "$_BACKUP_HOME" >/dev/null || {
    echo "ERR: $_BACKUP_HOME was not mounted.">&2;
    exit 1;
}
[ -w "$_BACKUP_HOME" ] || {
    echo "ERR: $_BACKUP_HOME is not writable.">&2;
    exit 2;
}

echo "INFO: $_LNAME[$$] started.";

mkdir -v -p "$_BACKUP_HOME/$_TIMESTAMP"

for _TARGET in ${_BACKUP_TARGETS[@]}; do
    echo "Backup \"$_TARGET\" to \"$_BACKUP_HOME/$_TIMESTAMP\"";
    mkdir -v -p "$_BACKUP_HOME/${_TIMESTAMP}$_TARGET";
    cp -v -f -Rp "$_TARGET"/* "$_BACKUP_HOME/${_TIMESTAMP}$_TARGET";
done;

echo "$_BACKUP_HOME/$_TIMESTAMP">"$_BACKUP_HOME/LATEST";

echo "INFO: $_LNAME[$$] end.";
exit 0;
